
import { Transaction } from '@/types/transaction';

// Example transactions for development
export const mockTransactions: Transaction[] = [
  {
    id: '1',
    title: 'Salary',
    amount: 5000,
    category: 'Income',
    date: '2023-04-01',
    type: 'income',
    fromAccount: 'Bank Account',
    source: 'manual',
  },
  {
    id: '2',
    title: 'Rent',
    amount: -1500,
    category: 'Housing',
    date: '2023-04-02',
    type: 'expense',
    fromAccount: 'Bank Account',
    source: 'manual',
  },
  {
    id: '3',
    title: 'Groceries',
    amount: -200,
    category: 'Food',
    date: '2023-04-03',
    type: 'expense',
    fromAccount: 'Credit Card',
    source: 'manual',
  },
  {
    id: '4',
    title: 'Internet Bill',
    amount: -80,
    category: 'Utilities',
    date: '2023-04-05',
    type: 'expense',
    fromAccount: 'Bank Account',
    source: 'manual',
  },
  {
    id: '5',
    title: 'Dinner',
    amount: -50,
    category: 'Food',
    date: '2023-04-10',
    type: 'expense',
    fromAccount: 'Cash',
    source: 'manual',
  },
  {
    id: '6',
    title: 'Gas',
    amount: -45,
    category: 'Transportation',
    date: '2023-04-12',
    type: 'expense',
    fromAccount: 'Credit Card',
    source: 'manual',
  },
  {
    id: '7',
    title: 'Freelance Work',
    amount: 1000,
    category: 'Income',
    date: '2023-04-15',
    type: 'income',
    fromAccount: 'Bank Account',
    source: 'manual',
  },
  {
    id: '8',
    title: 'Coffee',
    amount: -5,
    category: 'Food',
    date: '2023-04-20',
    type: 'expense',
    fromAccount: 'Cash',
    source: 'manual',
  }
];
