export const CATEGORY_COLOR_MAP: Record<string, string> = {
  Bills: 'text-orange-600',
  Education: 'text-indigo-600',
  Entertainment: 'text-purple-600',
  Food: 'text-amber-600',
  'Gifts & Donations': 'text-pink-600',
  Health: 'text-red-600',
  Housing: 'text-green-600',
  Kids: 'text-teal-600',
  'Personal Care': 'text-fuchsia-600',
  Services: 'text-yellow-600',
  Shopping: 'text-rose-600',
  Transfer: 'text-emerald-600',
  Transportation: 'text-blue-600',
  Travel: 'text-cyan-600',
  Utilities: 'text-gray-600',
  Income: 'text-lime-600',
  Other: 'text-zinc-600',
};
